// <auto-generated />
namespace LEARNIT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DeletePhotoDone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeletePhotoDone));
        
        string IMigrationMetadata.Id
        {
            get { return "201511060928269_DeletePhotoDone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
