//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTable()
        {
            this.Courses = new HashSet<Course>();
            this.Courses1 = new HashSet<Course>();
        }
    
        public int userId { get; set; }
        public string loginName { get; set; }
        public string userEmail { get; set; }
        public string userPassword { get; set; }
        public System.DateTime signUpDate { get; set; }
        public string userName { get; set; }
        public string userLocation { get; set; }
        public string userWebsite { get; set; }
        public string userPhoto { get; set; }
        public string userAbout { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses1 { get; set; }
    }
}
